"""Gmail integration.

Sends meeting summary reports via email to meeting attendees
after the meeting ends.
"""

from __future__ import annotations

import base64
import logging
from email.mime.text import MIMEText

from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials

logger = logging.getLogger(__name__)


class GmailService:
    """Sends meeting summary emails via the Gmail API."""

    def __init__(self, credentials: Credentials) -> None:
        self.service = build("gmail", "v1", credentials=credentials)

    def send_meeting_summary(
        self,
        to_emails: list[str],
        meeting_title: str,
        agenda: str,
        summary: str,
        decisions: list[str],
        open_items: list[str],
        deviation_count: int,
    ) -> bool:
        """Compose and send a meeting summary email to all attendees.

        Returns True if the email was sent successfully.
        """
        if not to_emails:
            logger.warning("No recipients for meeting summary email")
            return False

        subject = f"Meeting Summary: {meeting_title}"
        body = self._build_email_body(
            meeting_title, agenda, summary, decisions, open_items, deviation_count
        )

        try:
            message = MIMEText(body, "html")
            message["Subject"] = subject
            message["To"] = ", ".join(to_emails)

            raw = base64.urlsafe_b64encode(message.as_bytes()).decode("utf-8")
            self.service.users().messages().send(
                userId="me",
                body={"raw": raw},
            ).execute()

            logger.info("Meeting summary email sent to %d recipients", len(to_emails))
            return True

        except Exception:
            logger.exception("Failed to send meeting summary email")
            return False

    @staticmethod
    def _build_email_body(
        meeting_title: str,
        agenda: str,
        summary: str,
        decisions: list[str],
        open_items: list[str],
        deviation_count: int,
    ) -> str:
        """Build an HTML email body for the meeting summary."""
        decisions_html = ""
        if decisions:
            items = "".join(f"<li>{d}</li>" for d in decisions)
            decisions_html = f"<h3>Decisions Made</h3><ul>{items}</ul>"

        open_items_html = ""
        if open_items:
            items = "".join(f"<li>{item}</li>" for item in open_items)
            open_items_html = f"<h3>Open Items</h3><ul>{items}</ul>"

        agenda_html = agenda.replace("\n", "<br>")
        summary_html = summary.replace("\n", "<br>")

        return f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2>{meeting_title} - Meeting Summary</h2>
            <p style="color: #666; font-size: 12px;">
                Generated by Meeting Focus Tracker
            </p>

            <h3>Agenda</h3>
            <div style="background: #f5f5f5; padding: 12px; border-radius: 6px;">
                {agenda_html}
            </div>

            <h3>Summary</h3>
            <div style="padding: 12px; border-left: 3px solid #4285f4;">
                {summary_html}
            </div>

            {decisions_html}
            {open_items_html}

            <h3>Focus Score</h3>
            <p>Off-topic deviations detected: <strong>{deviation_count}</strong></p>

            <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
            <p style="color: #999; font-size: 11px;">
                This summary was auto-generated by Meeting Focus Tracker.
            </p>
        </div>
        """
